# Generated by Django 4.0.5 on 2022-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todolist_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='tdlist',
            new_name='tdlist_id',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
