# Generated by Django 4.0.5 on 2022-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tdlist_todoitem_tdlist_id_todoitem_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
