# Generated by Django 4.0.5 on 2022-07-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_todolist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProConList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.crew')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProConItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('pclist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.proconlist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
