services:
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/develop/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/app/
    ports:
      - "3000:3000"

  backend:
    build: ./backend/
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-}
